package it.polimi.ingsw.am23.model.enums;

public enum BuildingEffectName {
    CAVE_PAINTINGS_FOOD_PER_ARTIST_EFFECT,
    DOUBLE_BUILDER_END_GAME_EFFECT,
    DOUBLE_SHAMAN_WIN_EFFECT,
    END_GAME_POINTS_PER_CHARACTER_TYPE_EFFECT,
    END_GAME_POINTS_PER_COMPLETE_SET_EFFECT,
    EXTRA_DRAW_EFFECT,
    FLAT_END_GAME_POINTS_EFFECT,
    FOOD_FROM_TURN_ORDER_BONUS_EFFECT,
    FOOD_PER_COMPLETE_SET_EFFECT,
    FOOD_PER_INVENTOR_PAIR_EFFECT,
    HUNTING_REWARD_PER_HUNTER_EFFECT,
    NO_LOSS_LAST_SHAMAN_EFFECT,
    SHAMAN_BONUS_STARS_EFFECT,
    SUSTENANCE_DISCOUNT_PER_TYPE_EFFECT
}
